### ISSUE TITLE
RequestIdTooLong due to concatenating ids

### ISSUE THREAD

**Issue by nakhli** [listia/aws_agcod#3]
the partner id and the requestid are concatenated cf [code](https://github.com/listia/aws_agcod/blob/master/lib%2Faws_agcod%2Fcreate_gift_card.rb#L19))

I am getting 

`200 RequestIdTooLong - Request Id Too Long, Max allowed length is 19`

could we just use the provided request id? what is the rationale behind concatenating both ids?

**Comment by tubaxenor** [comment]
Yeah, same issue as described in #2, will make a change when I got some time, thanks!

**Comment by tubaxenor** [comment]
Fixed through https://github.com/listia/aws_agcod/commit/c468e1a66779e2af333e1208e7622b42b5a3c862

**Comment by nakhli** [comment]
The string is still long in my case. why should we concatenate the partner_id to the provided request id at all? why don't we "ask don't tell" here by letting the client manage the request id unicity as he sees fit?

**Comment by tubaxenor** [comment]
In https://s3.amazonaws.com/AGCOD/tech_spec/AGCODTechSpec.pdf

VI. AGCOD Service: Real-Time Request-Responses > 1. Definitions > 2. creationRequestId

> A unique identifier for every CreateGiftCard call that results in the creation of a
> gc. The partner must generate a new value for every Create request (except for retries). To keep this
> a globally unique transaction identifier, the partner needs to:
> 
>  Generate an alphanumeric value that is unique within the partner’s systems
> => ** Use the partnerId as a prefix to the …RequestId** <=
> 
> Note: that the total size limit on the field is 19 chars
> If a request comes in with this value repeated, the AGCOD Gateway will return the original status
> that was created the first time the creationRequestId was seen. 

The `=>...<=` part is actually the reason why I choose to prefix partner id as part of the creation request id.

**Comment by nakhli** [comment]
Thank you for the quick answer and for the great library :+1: 
on another topic: I don't see how we can access the `expiration_date` [here](https://github.com/listia/aws_agcod/blob/master/lib/aws_agcod/create_gift_card.rb#L27-L38)?

**Comment by tubaxenor** [comment]
> on another topic: I don't see how we can access the expiration_date here?

Yeah... I don't actually want to expose everything, but that sounds like a good attribute to add, can you make a PR or feature request as an issue? Thanks!
