### ISSUE TITLE
Error when we try to create a new gift card

### ISSUE THREAD

**Issue by lmbautista** [listia/aws_agcod#7]
We get the following error within the response after the request generated by the gem:

"Message"=>"class java.lang.String is not an expected Json type"

The initializer is similar to the one specified in the Readme:
  config.uri = "https://agcod-v2-eu-gamma.amazon.com"
  config.region  = "eu-west-1" # default
  config.timeout = 30          # default

Also we created a method based in your example:

 def create
      request_id = IbAgcod::KeyGenerator.generate_request_id
      amount = params[:amount]
      currency = "EUR" # default to USD, available types are: USD, EUR, JPY, CNY, CAD

```
  request = AGCOD::CreateGiftCard.new(request_id, amount, currency)

  # When succeed
  if request.success?
    request.claim_code # => code for the gift card
    request.gc_id # => gift card id
    request.request_id # => your request id
  else
    # When failed
    request.error_message # => Error response from AGCOD service
  end

  render json: request.to_json
end
```

We have debugged when the request is generated and we checked the body was a string instead of json

**Comment by tubaxenor** [comment]
Hi @lmbautista, I've tried the example using development credentials and it returns successful response.

``` ruby
request_id = "test"
amount = 10
currency = "USD"

request = AGCOD::CreateGiftCard.new(request_id, amount, currency)
# => #<AGCOD::CreateGiftCard:0x007fa53444ae90 @response=#<AGCOD::Response:0x007fa53446b6e0 @payload={"cardInfo"=>{"cardNumber"=>nil, "cardStatus"=>"Fulfilled", "expirationDate"=>nil, "value"=>{"amount"=>10.0, "currencyCode"=>"USD"}}, "creationRequestId"=>"Listitest", "gcClaimCode"=>"2BTW-BDBKQP-A6PF", "gcExpirationDate"=>nil, "gcId"=>"AILY4VGRT2EM0", "status"=>"SUCCESS"}, @status="SUCCESS">>

request.to_json
# => "{\"response\":{\"payload\":{\"cardInfo\":{\"cardNumber\":null,\"cardStatus\":\"Fulfilled\",\"expirationDate\":null,\"value\":{\"amount\":10.0,\"currencyCode\":\"USD\"}},\"creationRequestId\":\"Listitest\",\"gcClaimCode\":\"2BTW-BDBKQP-A6PF\",\"gcExpirationDate\":null,\"gcId\":\"AILY4VGRT2EM0\",\"status\":\"SUCCESS\"},\"status\":\"SUCCESS\"}}"
```

I don't have `EUR` enabled as our available currency, so can't really test it using exact same params, but I think from the error message you got `"Message"=>"class java.lang.String is not an expected Json type"`, it looks like the error is from AWS service and not from the client side.

Please reopen if you think/find out anything is wrong from the source code, thanks.

**Comment by lmbautista** [comment]
Despite I changed the currency value as you said, I keep having the same error message. It comes from AWS as we guess but the problem was fixed when we added in our local version the following method to_json for the body method.

``` ruby
# /lib/aws_agcod/request.rb:16
@response = Response.new(HTTParty.post(uri, body: body.to_json, headers: signed_headers, timeout: AGCOD.config.timeout).body)
```

We keep having a problem to get a right response. It's because of we don't have the digital signature

> The request signature we calculated does not match the signature you provided

**Comment by tubaxenor** [comment]
Hmm... The `body` method already casted w/ `.to_json`: https://github.com/listia/aws_agcod/blob/master/lib/aws_agcod/request.rb#L43

It's a bit weird that you need to do it again... Is it possible that the `to_json` method was overridden in other places? Can you give me what's the `body` looks like before you do `.to_json` again?

**Comment by lmbautista** [comment]
The error was because of we pass the amount as string so it generated that error where It's not really specify the real error.

Thanks and sorry for the disturbances!
